---
title: "sql-workshop"
author: "Han Wang"
date: "03/26/2024"
output: html_document
---

## Connect to AMW MySQL Database
```{r}
install.packages("DBI")
install.packages("RMySQL")

library(DBI)
library(RMySQL)

db_user <- 'admin'
db_password <- 'sql032624'
db_name <- 'testdb'
db_host <- 'sqltest.ct5uulgrqvyh.us-east-2.rds.amazonaws.com'
db_port <- 3306

mydb <- dbConnect(MySQL(), user = db_user, password = db_password, dbname = db_name, host = db_host, port = db_port)

summary(mydb)
```

## Load OU Data
```{r}
#Student demographic data
studentInfo <- read.csv("studentInfo.csv", header = TRUE)
#Student assessment data
studentAssessment <- read.csv("studentAssessment.csv", header = TRUE)
#Course data
courses <- read.csv("courses.csv", header = TRUE)
studentRegistration <- read.csv("studentRegistration.csv", header = TRUE)
```

## Write data to the DB using the DBI package
```{r}
#List the tables in the DB
dbListTables(mydb)

#Write a new table to the DB
dbWriteTable(mydb, "studentInfo", studentInfo)
dbWriteTable(mydb, "studentAssessment", studentAssessment)
dbWriteTable(mydb, "courses", courses)
dbWriteTable(mydb, "studentRegistration", studentRegistration)

#List tables to see that table was added
dbListTables(mydb)

#Read a particular table
dbReadTable(mydb, 'studentInfo')

#EXERCISE 1
#Make two toy data sets with at least three variables and at least 30 rows each in them. Have a mix of numeric and character variables. Transfer these dataframes to your SQL database using the DBI commands. Name the tables whatever you like.

# Load necessary library
library(tibble)

# Data Set 1: Employee Details
set.seed(0) # For reproducibility
EmployeeDetails <- tibble(
  EmployeeID = 1:30,
  Department = sample(c("HR", "IT", "Finance", "Sales"), 30, replace = TRUE),
  Salary = sample(30000:100000, 30, replace = TRUE)
)

# Data Set 2: Product Sales
ProductSales <- tibble(
  ProductID = 1:30,
  ProductName = paste("Product", 1:30),
  UnitsSold = sample(1:500, 30, replace = TRUE)
)

# Create Tables
dbWriteTable(mydb, "employeeDetails", EmployeeDetails)
dbWriteTable(mydb, "productSales", ProductSales)

# List of Tables
dbListTables(mydb)

# Show table
dbReadTable(mydb, "productSales")
```

## Getting into SQL - READING
```{r}
#Query a portion of the database (always returns dataframe)
dbGetQuery(mydb, "SELECT * FROM studentInfo LIMIT 10;")

dbGetQuery(mydb, "SELECT * FROM studentInfo ORDER BY id_student LIMIT 10;")

dbGetQuery(mydb, "SELECT id_student, gender FROM studentInfo ORDER BY id_student DESC LIMIT 10;") #Order listed will be reflected in order in table

dbGetQuery(mydb, "SELECT id_student AS 'Student ID', gender FROM studentInfo LIMIT 10;") #SQL Standard single quotes for literal strings and double quotes for everything else but that conflicts with R

#Count the number of rows
dbGetQuery(mydb, "SELECT COUNT(*) FROM studentAssessment;")

#Using a WHERE statement on all columns
dbGetQuery(mydb, "SELECT COUNT(*) FROM studentAssessment WHERE score > 50;")

#Using a WHERE statement on a single column (will not include missing data)
dbGetQuery(mydb, "SELECT COUNT(score) FROM studentAssessment WHERE score > 50;")

#Using an AND statement
dbGetQuery(mydb, "SELECT COUNT(*) FROM studentAssessment WHERE score > 50 AND id_assessment = '1752';")

#EXERCISE 2
#Read one of your toy data tables, make sure the output is ordered in descending order, you rename one of the variables and the output is limited to the first 20 rows.
dbGetQuery(mydb,"select ProductID as ID, ProductName as Name from productSales order by ID desc limit 20;")

#Read the other table according to a condition of one of the variables.
dbGetQuery(mydb,"select * from productSales where ProductID = 15;")
```

## Getting into SQL - UPDATING
```{r}
#Count rows
dbGetQuery(mydb, "SELECT COUNT(*) FROM studentAssessment;")

#Add a row
dbGetQuery(mydb, "INSERT INTO studentAssessment (id_assessment, id_student, date_submitted, is_banked, score) VALUES ('00001', '1', '20', '0', '50');")

#Count rows again
dbGetQuery(mydb, "SELECT COUNT(*) FROM studentAssessment;")

#View inserted row
dbGetQuery(mydb, "SELECT * FROM studentAssessment ORDER BY id_student LIMIT 10;")

#Add a row with missing values
dbGetQuery(mydb, "INSERT INTO studentAssessment (id_assessment, id_student, date_submitted) VALUES ('00001', '1', '20');")

#View inserted row
dbGetQuery(mydb, "SELECT * FROM studentAssessment ORDER BY id_student LIMIT 10;")

#Update a row
dbGetQuery(mydb, "UPDATE studentAssessment SET score = '20' WHERE id_student = 1;")

dbGetQuery(mydb, "SELECT id_student, score FROM studentAssessment ORDER BY id_student LIMIT 10;")

#Update a row with NULL
dbGetQuery(mydb, "UPDATE studentAssessment SET score = 'NULL' WHERE id_student = 6516;")

#Delete a row (destructive)
dbGetQuery(mydb, "DELETE FROM studentAssessment WHERE id_student = 1;")

dbGetQuery(mydb, "SELECT * FROM studentAssessment ORDER BY id_student LIMIT 10;")

#EXERCISE 3
#Insert a new row in one of your toy data tables leaving one variable empty. Change one value in your other table. Display your new tables. Delete the row you edited and the row you inserted. 
dbGetQuery(mydb, "insert into productSales (ProductID, ProductName, UnitsSold) VALUES ('9999', 'toy', '200');")
dbGetQuery(mydb, "SELECT * FROM productSales where ProductID=9999;")
dbGetQuery(mydb, "UPDATE productSales SET UnitsSold = '500' WHERE ProductID = 9999;")
dbGetQuery(mydb, "SELECT * FROM productSales where ProductID = 9999;")
dbGetQuery(mydb, "DELETE FROM productSales WHERE ProductID = 9999;")

```

## Add/Deleting Table
```{r}
#Creating a new table in SQL
dbGetQuery(mydb,"CREATE TABLE test (
  score INTEGER, 
  student TEXT
  );")

dbListTables(mydb)

#Inserting data into the table
dbGetQuery(mydb, "INSERT INTO test VALUES ( 10, 'Amy' );")
dbGetQuery(mydb, "INSERT INTO test VALUES ( 11, 'Jen' );")
dbGetQuery(mydb, "INSERT INTO test VALUES ( 9, 'Frank' );")

dbGetQuery(mydb, "SELECT * FROM test;")

#Inserting a NULL row
dbGetQuery(mydb, "INSERT INTO test DEFAULT VALUES;")

dbGetQuery(mydb,"INSERT INTO test (score, student) SELECT score, id_student FROM studentAssessment;")

dbGetQuery(mydb, "SELECT * FROM test;")

# NULL Value

#NULL is a state (similar to R), represents the lack of a value. But is not compatible with R backend so this code doesn't work as part of dbGetQuery()

#This doesn't work because NULL is not a value (it cannot be "equal" to anything as it is ignored)
SELECT * FROM test WHERE score = NULL;

#Instead use "is"
dbGetQuery(mydb, "SELECT * FROM test WHERE score is NULL;")

#Delete a table
dbGetQuery(mydb, "DROP TABLE test;")

dbGetQuery(mydb, "SELECT * FROM test;") #This should produce an error, table has been dropped

#Delete a table if it exists
dbGetQuery(mydb, "DROP TABLE IF EXISTS test;")

#EXERCISE 4
#Create a table that is exactly the same as your first toy data table but this time use SQL commands. Display your new table. Then delete the original table. 
# Create a copy of the table

dbGetQuery(mydb, "CREATE TABLE IF NOT EXISTS EmployeeDetailsCopy (
  EmployeeID INTEGER, 
  Department VARCHAR(255), 
  Salary INTEGER
);")

# Copy data to the new table
dbGetQuery(mydb, "INSERT INTO EmployeeDetailsCopy (EmployeeID, Department, Salary) SELECT EmployeeID, Department, Salary FROM employeeDetails;")

# Display the new table
dbGetQuery(mydb, "SELECT * FROM EmployeeDetailsCopy;")

# Drop the original table
dbGetQuery(mydb, "DROP TABLE employeeDetails;")


```

# Constraints
```{r}
#Create table where student column *cannot* be NULL
dbGetQuery(mydb,"CREATE TABLE test2 (
  score INTEGER, 
  student TEXT NOT NULL
  );")

dbGetQuery(mydb, "DROP TABLE IF EXISTS test2;")

#Create table where score column defaults to zero

dbGetQuery(mydb,"CREATE TABLE test2 (
   score INTEGER DEFAULT 0, 
   student TEXT
   );")

dbGetQuery(mydb,"INSERT INTO test2 (score, student) VALUES ('1', 'A');")
dbGetQuery(mydb,"INSERT INTO test2 (student) VALUES ('B');")

dbGetQuery(mydb, "SELECT * FROM test2;")

dbGetQuery(mydb, "DROP TABLE IF EXISTS test2;")


# Create a table where column must have unique value
dbGetQuery(mydb,"CREATE TABLE test2 (
  score INTEGER UNIQUE, 
  student TEXT
  );")

dbGetQuery(mydb,"INSERT INTO test2 (score, student) VALUES ('1', 'A');")

#Error because of unique
dbGetQuery(mydb,"INSERT INTO test2 (score, student) VALUES ('1', 'A');")

#NULL is exempt
dbGetQuery(mydb,"INSERT INTO test2 (score, student) VALUES (NULL, 'A');")
dbGetQuery(mydb,"INSERT INTO test2 (score, student) VALUES (NULL, 'A');")

#EXERCISE 5
#Recreate one of your toy data tables with the constraint that for one of the integer variables the default value will be zero. Test your table by inserting some empty values. Display your new tables. Then delete your table.  

dbGetQuery(mydb,"CREATE TABLE employeeDetails (
  ProductID INTEGER NOT NULL, 
  ProductName TEXT,
  UnitsSold INTEGER DEFAULT 0
  );")

dbGetQuery(mydb,"INSERT INTO employeeDetails (ProductID, ProductName) VALUES (567, 'Disc');")

# UnitsSold set to default value 0
dbGetQuery(mydb, "Select * from employeeDetails")

dbGetQuery(mydb,"Drop Table employeeDetails;")

```


# Adding a column with a default value
```{r}
#Add a column with default value 1
dbGetQuery(mydb, "ALTER TABLE studentAssessment ADD email INTEGER DEFAULT 1 ")

dbGetQuery(mydb, "SELECT * FROM studentAssessment LIMIT 10;")

#Delete a column
dbGetQuery(mydb, "ALTER TABLE studentAssessment DROP COLUMN email;")

#EXERCISE 6
#Add a column to one of your toy data tables with a default value of 3. Display your new table. Delete this column.

dbGetQuery(mydb,"alter table EmployeeDetailsCopy add email integer default 3;")
dbGetQuery(mydb, "select * from EmployeeDetailsCopy;")
```


# ID Columns
```{r}
dbGetQuery(mydb,"CREATE TABLE test3 (
  id INTEGER AUTO_INCREMENT PRIMARY KEY, #Not standard syntax
  score INTEGER, 
  student TEXT
  );")

dbGetQuery(mydb,"INSERT INTO test3 (score, student) VALUES (1, 'A');")
dbGetQuery(mydb,"INSERT INTO test3 (score, student) VALUES (5, 'B');")

dbGetQuery(mydb, "SELECT * FROM test3;")

dbGetQuery(mydb, "DROP TABLE IF EXISTS test3;")

#EXERCISE 7
#Create a new table with four variables and a primary key that is a sequential id value.

dbGetQuery(mydb,"CREATE TABLE newtable (
  id INTEGER AUTO_INCREMENT PRIMARY KEY, #Not standard syntax
  score INTEGER, 
  student TEXT,
  email TEXT
  );")

dbGetQuery(mydb,"INSERT INTO newtable (score, student) VALUES (5, 'B');")
dbGetQuery(mydb,"INSERT INTO newtable (score, student, email) VALUES (5, 'B', 'wh@hw.edu');")

dbGetQuery(mydb, "SELECT * FROM newtable;")

dbGetQuery(mydb, "DROP TABLE IF EXISTS newtable;")

```

## Filtering (WHERE)
```{r}
dbGetQuery(mydb, "SELECT id_student, date_submitted FROM studentAssessment WHERE date_submitted > 550 ORDER BY date_submitted DESC;")

#OR Statement
dbGetQuery(mydb, "SELECT id_student, date_submitted FROM studentAssessment WHERE date_submitted > 550 OR date_submitted < 2 ORDER BY date_submitted DESC;")

#AND Statement
dbGetQuery(mydb, "SELECT id_student, date_submitted FROM studentAssessment WHERE date_submitted > 550 AND id_student = 325750 ORDER BY date_submitted DESC;")

#LIKE - Character string matches a pattern
# %aaa% - Finds any values that have "aaa" in any position
# aaa% - Finds any values that start with "aaa"
# _aaa% - Finds any values that have aaa in the second, third, fourth positions

dbGetQuery(mydb, "SELECT id_student, gender, region FROM studentInfo WHERE region LIKE '%Region%';")

#Begin with 'Region'
dbGetQuery(mydb, "SELECT id_student, gender, region FROM studentInfo WHERE region LIKE 'Region%';")

#End with 'Region'
dbGetQuery(mydb, "SELECT id_student, gender, region FROM studentInfo WHERE region LIKE '%Region';")

#'c' is the second letter
dbGetQuery(mydb, "SELECT id_student, gender, region FROM studentInfo WHERE region LIKE '_c%';")

#IN
dbGetQuery(mydb, "SELECT id_student, gender, region FROM studentInfo WHERE region IN ('Wales','Ireland');")

#EXERCISE 8
#Query one of your original toy data tables, for two different conditions. 
dbGetQuery(mydb,"select * from EmployeeDetailsCopy;")
dbGetQuery(mydb,"select * from EmployeeDetailsCopy where Department like '%Sales%' and Salary > 50000;")


```

## Removing Duplicates
```{r}
dbGetQuery(mydb, "SELECT DISTINCT region FROM studentInfo;")

dbGetQuery(mydb, "SELECT DISTINCT region, gender FROM studentInfo;")

#EXERCISE 9
#Insert a duplicate row into one of your toy data tables. Then query the table without including duplicates.
dbGetQuery(mydb, "Insert into EmployeeDetailsCopy (EmployeeID, Department, Salary, email) VALUES(30, 'Sales', 79217, 3)")

dbGetQuery(mydb,"select distinct EmployeeID, Department, Salary, email from EmployeeDetailsCopy where Department like '%Sales%' and Salary > 50000;")


```

## Conditional Expressions (non-standard)
```{r}
dbGetQuery(mydb, "CREATE TABLE booltest (a INTEGER, b INTEGER);")
dbGetQuery(mydb, "INSERT INTO booltest VALUES (1, 0);")
dbGetQuery(mydb, "SELECT * FROM booltest;")

dbGetQuery(mydb,"SELECT
  CASE WHEN a THEN 'true' ELSE 'false' END as boolA,
  CASE WHEN b THEN 'true' ELSE 'false' END as boolB
  FROM booltest")

dbGetQuery(mydb,"SELECT
  CASE a WHEN 1 THEN 'true' ELSE 'false' END as boolA,
  CASE b WHEN 1 THEN 'true' ELSE 'false' END as boolB
  FROM booltest")
```

#Relationships (JOIN) - *Slide*
```{r}

#This will take a while because of the architecture we are using
#dbGetQuery(mydb,"SELECT id_student, gender, region, date_registration
          #FROM studentInfo
          #JOIN studentRegistration
          #ON studentInfo.id_student = studentRegistration.id_student
          #;")

dbGetQuery(mydb, "CREATE TABLE left_table (id INTEGER, description TEXT);")
dbGetQuery(mydb, "CREATE TABLE right_table (id INTEGER, description TEXT);")

dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 1, 'left 01');")
dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 2, 'left 02');")
dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 3, 'left 03');")
dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 4, 'left 04');")
dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 5, 'left 05');")
dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 6, 'left 06');")
dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 7, 'left 07');")
dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 8, 'left 08');")
dbGetQuery(mydb, "INSERT INTO left_table VALUES ( 9, 'left 09');")

dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 6, 'left 06');")
dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 7, 'left 07');")
dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 8, 'left 08');")
dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 9, 'left 09');")
dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 10, 'left 10');")
dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 11, 'left 11');")
dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 12, 'left 12');")
dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 13, 'left 13');")
dbGetQuery(mydb, "INSERT INTO right_table VALUES ( 14, 'left 14');")

dbGetQuery(mydb, "SELECT * FROM left_table;")
dbGetQuery(mydb, "SELECT * FROM right_table;")

#Everything that matches between tables
dbGetQuery(mydb,"SELECT l.description AS left_table, r.description AS right_table 
           FROM left_table AS l 
           JOIN right_table AS r ON l.id = r.id")

#Evereything from right, matches from left
dbGetQuery(mydb,"SELECT l.description AS left_table, r.description AS right_table 
           FROM left_table AS l 
           RIGHT JOIN right_table AS r ON l.id = r.id")

#Evereything from left, matches from right
dbGetQuery(mydb,"SELECT l.description AS left_table, r.description AS right_table 
           FROM left_table AS l 
           LEFT JOIN right_table AS r ON l.id = r.id")

#Union
dbGetQuery(mydb, "SELECT * FROM left_table
           UNION
           SELECT * FROM right_table;")


#EXERCISE 10
# Create an a common id variable in your two toy data tables. Then do join those tables so that your query returns all the values from one table and only those that match from the other. 

dbGetQuery(mydb,"select * from EmployeeDetailsCopy;")
dbGetQuery(mydb,"select * from productSales;")

dbGetQuery(mydb, "select * from EmployeeDetailsCopy e left join productSales p on e.EmployeeID = p.ProductID")



```

# Disconnect your database
```{r}
dbDisconnect(mydb)
```

